//! The same non-JIT, capability-only typesetter on iPad and Mac. Every guest
//! function entry and loop (TeX, fonts, BibTeX and PDF) has a cancellation gate.
//! A trap stays in generated C; no Rust or Swift host frame is skipped.
mod files;
mod ffi;
mod wasi;
use files::{Budget, Bundle, Directory, Log, ResourceFile};
use std::{path::Path, sync::{Arc, atomic::{AtomicBool, Ordering}}, time::{Duration, Instant}};
use wasi_common::{WasiCtx, sync::WasiCtxBuilder, pipe::WritePipe};

const LINEAR_BYTES: usize = 320*1024*1024;
static ENGINE_SERIAL: std::sync::Mutex<()> = std::sync::Mutex::new(());
struct NativeState { wasi: WasiCtx, started: Instant, timeout: Duration, cancelled: *const AtomicBool, failure: Option<String> }
impl NativeState {
    fn check(&mut self) -> bool {
        if unsafe { &*self.cancelled }.load(Ordering::Relaxed) { self.failure = Some("typesetter_cancelled".into()); }
        else if self.started.elapsed() >= self.timeout { self.failure = Some("typesetter_deadline".into()); }
        self.failure.is_some()
    }
}
#[unsafe(no_mangle)]
unsafe extern "C" fn nb_typesetter_should_stop(state: *mut NativeState) -> i32 { i32::from(unsafe { &mut *state }.check()) }
unsafe extern "C" { fn nb_engine_run(context: *mut std::ffi::c_void, bytes: *mut u8, capacity: usize, used: *mut usize, format: i32) -> i32; }
pub struct Runtime { bundle: Arc<Bundle>, format: ResourceFile, fonts: ResourceFile }
#[derive(Debug)]
pub struct Output { pub pdf: Vec<u8>, pub synctex: Vec<u8>, pub log: String, pub memory_bytes: usize, pub input_reads: Vec<u8> }
impl Runtime {
    pub fn new(bundle: &Path, format: &Path, fonts: &Path) -> Self {
        Self { bundle: Arc::new(Bundle::new(bundle)),
            format: ResourceFile::new(format, 32*1024*1024), fonts: ResourceFile::new(fonts, 2*1024*1024) }
    }
    pub fn compile(&self, entrypoint: &str, files: Vec<(String, Vec<u8>)>, date: u64,
        timeout: Duration, cancelled: &AtomicBool) -> Result<Output, String> {
        if !Directory::valid_path(entrypoint) || !entrypoint.ends_with(".tex") { return Err("typesetter_entrypoint_invalid".into()); }
        let source = files.iter().find(|(path, _)| path == entrypoint).ok_or("typesetter_entrypoint_missing")?;
        if source.1.len() > 4*1024*1024 || std::str::from_utf8(&source.1).is_err() { return Err("typesetter_entrypoint_encoding_or_limit".into()); }
        self.run(entrypoint, files, date, timeout, cancelled, 0)
    }
    /// Build-time only: the shipped immutable format is generated by this same
    /// engine and pinned distribution, never by a user's mutable TeX cache.
    pub fn generate_format(&self) -> Result<Vec<u8>, String> {
        self.run("", vec![], 0, Duration::from_secs(30), &AtomicBool::new(false), 1).map(|v| v.pdf)
    }
    pub fn convert_svg(&self, source: &str, timeout: Duration, cancelled: &AtomicBool) -> Result<Output, String> {
        self.run("image.svg", vec![("image.svg".into(), source.as_bytes().to_vec())], 0, timeout, cancelled, 2)
    }
    fn run(&self, entrypoint: &str, assets: Vec<(String, Vec<u8>)>, date: u64,
        timeout: Duration, cancelled: &AtomicBool, operation: i32) -> Result<Output, String> {
        let format = operation == 1; let image = operation == 2;
        if assets.len() > 4096 || assets.iter().try_fold(0usize, |n, a| n.checked_add(a.1.len())).is_none_or(|n| n > 16*1024*1024)
            || (image && assets.first().is_some_and(|a| a.1.len() > 8*1024*1024)) {
            return Err("typesetter_input_limit".into());
        }
        let _serial = ENGINE_SERIAL.try_lock().map_err(|_| "typesetter_busy".to_string())?;
        let started = Instant::now();
        let check = || {
            if cancelled.load(Ordering::Relaxed) { Err("typesetter_cancelled".to_string()) }
            else if started.elapsed() >= timeout.min(Duration::from_secs(30)) { Err("typesetter_deadline".to_string()) } else { Ok(()) }
        };
        check()?;
        let budget = Arc::new(Budget::default());
        let resources = files::ResourceCache::new(&budget);
        let (input, input_reads) = Directory::tracked_input(&budget);
        for (name, data) in assets {
            if !Directory::valid_path(&name) || name == "notebook.sty" { return Err("typesetter_file_path_invalid".into()); }
            input.put(&name, data).map_err(|e| format!("typesetter_namespace_invalid: {e}"))?;
        }
        let output = Directory::new(true, &budget);
        let bundle = Directory::bundle(self.bundle.clone(), false, &budget, &resources);
        if !format && !image {
            bundle.put_resource("latex.fmt", self.format.bytes()?).map_err(|e| e.to_string())?;
            bundle.put("notebook.sty", include_bytes!("../resources/notebook.sty").to_vec()).map_err(|e| e.to_string())?;
        }
        let fonts = Directory::bundle(self.bundle.clone(), true, &budget, &resources);
        fonts.put_resource("notebook-fonts.tsv", self.fonts.bytes()?).map_err(|e| e.to_string())?;
        let log = Log::default();
        let mut builder = WasiCtxBuilder::new();
        builder.env("TECTONIC_CACHE_DIR", "/output").map_err(|e| e.to_string())?
            .env("TECTONIC_FONT_DIR", "/fonts").map_err(|e| e.to_string())?
            .env("SOURCE_DATE_EPOCH", &date.to_string()).map_err(|e| e.to_string())?
            .env("NOTEBOOK_ENTRYPOINT", entrypoint).map_err(|e| e.to_string())?;
        let wasi = builder.build();
        wasi.set_stdout(Box::new(WritePipe::new(log.clone()))); wasi.set_stderr(Box::new(WritePipe::new(log.clone())));
        for (name, dir) in [("/input", input), ("/output", output.clone()), ("/bundle", bundle), ("/fonts", fonts)] {
            wasi.push_preopened_dir(Box::new(dir), name).map_err(|e| e.to_string())?;
        }
        // AOT WebAssembly uses this one fixed mapping. Each guest load/store is
        // bounds checked; memory.grow changes its extent without reallocating.
        let mut arena = memmap2::MmapMut::map_anon(if format { 512*1024*1024 } else { LINEAR_BYTES }).map_err(|e| e.to_string())?;
        let mut native = NativeState { wasi, started, timeout: timeout.min(Duration::from_secs(30)), cancelled, failure: None };
        let mut memory_bytes = 0;
        let status = unsafe { nb_engine_run((&mut native as *mut NativeState).cast(), arena.as_mut_ptr(), arena.len(), &mut memory_bytes, operation) };
        drop(arena);
        // A guest may treat an I/O errno as an optional missing font. Failure
        // to open the pinned archive is not an optional resource: never accept
        // its blank/partial PDF as a successful rendering.
        if let Some(error) = budget.resource_failure() { return Err(error); }
        if let Some(error) = native.failure { return Err(format!("{error}\n{}", String::from_utf8_lossy(&log.0.lock().unwrap()))); }
        drop(native.wasi);
        check()?;
        let log = String::from_utf8_lossy(&log.0.lock().unwrap()).into_owned();
        if status != 0 { return Err(format!("typesetter_error({status}): {log}")); }
        if format { return Ok(Output { pdf: output.take("latex.fmt").ok_or_else(|| format!("typesetter_no_format: {log}"))?, synctex: vec![], log, memory_bytes, input_reads: input_reads.bytes()? }); }
        let base = Path::new(entrypoint).file_stem().and_then(|v| v.to_str()).unwrap_or("image");
        let pdf = output.take(&format!("{base}.pdf")).ok_or_else(|| format!("typesetter_no_pdf: {log}"))?;
        let synctex = output.take(&format!("{base}.synctex.gz")).unwrap_or_default();
        if !pdf.starts_with(b"%PDF-") || pdf.len() > 16*1024*1024 || synctex.len() > 4*1024*1024 { return Err("typesetter_output_limit".into()); }
        Ok(Output { pdf, synctex, log, memory_bytes, input_reads: input_reads.bytes()? })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    /// Runs the production AOT kernel, not a host TeX executable. Invoke with
    /// NOTEBOOK_TYPESETTER_TEST_RESOURCES pointing at its pinned resources.
    #[test]
    #[ignore = "requires the prepared pinned TeX distribution and AOT kernel"]
    fn file_document_shipout_and_sandbox() {
        let resources = std::env::var("NOTEBOOK_TYPESETTER_TEST_RESOURCES").expect("pinned test resources");
        let root = Path::new(&resources);
        let runtime = Runtime::new(&root.join("texlive.zip"), &root.join("latex.fmt"), &root.join("fonts.tsv"));
        let compile = |entry: &str, files: Vec<(&str, &str)>| runtime.compile(entry,
            files.into_iter().map(|(path, source)| (path.into(), source.as_bytes().to_vec())).collect(),
            0, Duration::from_secs(30), &AtomicBool::new(false));
        let document = r"\documentclass{article}
\usepackage[paperwidth=300pt,paperheight=400pt,margin=25pt]{geometry}
\usepackage{notebook}\usepackage{styles/local}
\begin{document}\input{chapters/one}
\begin{figure}[p]\NotebookInteractive[id=osc,width=180pt,height=100pt]{programs/osc}\caption{Live}\label{fig:live}\end{figure}
See figure~\ref{fig:live}. \cite{example}\bibliographystyle{plain}\bibliography{refs/library}\end{document}";
        let files = vec![("main.tex", document), ("chapters/one.tex", "A real included chapter. \\localword"),
            ("styles/local.sty", "\\ProvidesPackage{styles/local}\\newcommand\\localword{LOCAL}"),
            ("refs/library.bib", "@book{example,author={A. Author},title={A real bibliography},year={2026}}")];
        let output = compile("main.tex", files.clone()).expect("multi-file document");
        assert!(!output.synctex.is_empty());
        assert!(output.log.contains("running BibTeX"));
        let nested = compile("text/main.tex", vec![("text/main.tex", "\\documentclass{article}\\begin{document}\\input{chapters/a}\\end{document}"),
            ("chapters/a.tex", "Nested entrypoint and document-root input.")]).expect("nested entrypoint");
        assert!(!nested.synctex.is_empty());
        let breakable = compile("main.tex", vec![("main.tex", r"\documentclass{article}\usepackage[paperheight=300pt,margin=25pt]{geometry}\usepackage{notebook}\begin{document}\NotebookInteractive[id=tall,width=100pt,height=650pt,breakable]{programs/tall}\end{document}")]).expect("breakable region");
        assert!(!breakable.synctex.is_empty()); // Geometry is checked through the shared Swift projector.
        assert!(compile("main.tex", vec![("main.tex", r"\documentclass{article}\usepackage{notebook}\begin{document}\NotebookInteractive[id=a,width=10pt,height=10pt]{p}\NotebookInteractive[id=a,width=10pt,height=10pt]{p}\end{document}")]).unwrap_err().contains("Duplicate interactive id"));
        assert!(compile("main.tex", vec![("main.tex", r"\documentclass{article}\begin{document}\input{/Users/amir/.codex/config.toml}\end{document}")]).is_err());
        assert!(compile("../main.tex", files).unwrap_err().contains("entrypoint_invalid"));
        let cancelled = AtomicBool::new(true);
        assert!(runtime.compile("main.tex", vec![("main.tex".into(), document.as_bytes().to_vec())], 0, Duration::from_secs(30), &cancelled).unwrap_err().contains("cancelled"));
        let loop_source = r"\documentclass{article}\begin{document}\def\forever{\forever}\forever\end{document}";
        assert!(runtime.compile("main.tex", vec![("main.tex".into(), loop_source.as_bytes().to_vec())], 0, Duration::from_millis(100), &AtomicBool::new(false)).unwrap_err().contains("deadline"));
        assert!(compile("main.tex", vec![("main.tex", document), ("chapters/one.tex", "Recovered"), ("styles/local.sty", "\\ProvidesPackage{styles/local}"), ("refs/library.bib", "@book{example,title={Recovery},year={2026}}")]).is_ok());
    }
}
