//! The same non-JIT, capability-only typesetter on iPad and Mac. Every guest
//! basic block (TeX, fonts, BibTeX and PDF) has a bounded cancellation checkpoint.
//! A trap stays in generated C; no Rust or Swift host frame is skipped.
mod files;
mod ffi;
mod wasi;
use files::{Budget, Bundle, Directory, Log};
use std::{path::Path, sync::{Arc, atomic::{AtomicBool, Ordering}}, time::{Duration, Instant}};
use wasi_common::{WasiCtx, sync::WasiCtxBuilder, pipe::WritePipe};

const LINEAR_BYTES: usize = 320*1024*1024;
static ENGINE_SERIAL: std::sync::Mutex<()> = std::sync::Mutex::new(());
struct NativeState { wasi: WasiCtx, started: Instant, timeout: Duration, cancelled: *const AtomicBool, failure: Option<String> }
impl NativeState {
    fn check(&mut self) -> bool {
        if unsafe { &*self.cancelled }.load(Ordering::Relaxed) { self.failure = Some("typesetter_cancelled".into()); }
        else if self.started.elapsed() >= self.timeout { self.failure = Some("typesetter_deadline".into()); }
        self.failure.is_some()
    }
}
#[unsafe(no_mangle)]
unsafe extern "C" fn nb_typesetter_should_stop(state: *mut NativeState) -> i32 { i32::from(unsafe { &mut *state }.check()) }
unsafe extern "C" { fn nb_engine_run(context: *mut std::ffi::c_void, bytes: *mut u8, capacity: usize, used: *mut usize, format: i32) -> i32; }
pub struct Runtime { bundle: Arc<Bundle>, format: Vec<u8>, fonts: Vec<u8> }
pub struct Output { pub pdf: Vec<u8>, pub synctex: Vec<u8>, pub log: String, pub memory_bytes: usize }
impl Runtime {
    pub fn new(bundle: &Path, format: Vec<u8>, fonts: Vec<u8>) -> Result<Self, String> {
        if format.len() > 32*1024*1024 || fonts.len() > 2*1024*1024 { return Err("typesetter_resource_limit".into()); }
        Ok(Self { bundle: Arc::new(Bundle::open(bundle)?), format, fonts })
    }
    pub fn compile(&self, source: &str, assets: Vec<(String, Vec<u8>)>, date: u64,
        timeout: Duration, cancelled: &AtomicBool) -> Result<Output, String> {
        self.run(source, assets, date, timeout, cancelled, 0)
    }
    /// Build-time only: the shipped immutable format is generated by this same
    /// engine and pinned distribution, never by a user's mutable TeX cache.
    pub fn generate_format(&self) -> Result<Vec<u8>, String> {
        self.run("", vec![], 0, Duration::from_secs(30), &AtomicBool::new(false), 1).map(|v| v.pdf)
    }
    pub fn convert_svg(&self, source: &str, timeout: Duration, cancelled: &AtomicBool) -> Result<Output, String> {
        self.run(source, vec![], 0, timeout, cancelled, 2)
    }
    fn run(&self, source: &str, assets: Vec<(String, Vec<u8>)>, date: u64,
        timeout: Duration, cancelled: &AtomicBool, operation: i32) -> Result<Output, String> {
        let format = operation == 1; let image = operation == 2;
        if source.len() > (if image { 8 } else { 4 })*1024*1024 || assets.len() > 128 || assets.iter().map(|a| a.1.len()).sum::<usize>() > 16*1024*1024 {
            return Err("typesetter_input_limit".into());
        }
        let _serial = ENGINE_SERIAL.try_lock().map_err(|_| "typesetter_busy".to_string())?;
        let started = Instant::now();
        let check = || {
            if cancelled.load(Ordering::Relaxed) { Err("typesetter_cancelled".to_string()) }
            else if started.elapsed() >= timeout.min(Duration::from_secs(30)) { Err("typesetter_deadline".to_string()) } else { Ok(()) }
        };
        check()?;
        let budget = Arc::new(Budget::default());
        let input = Directory::new(false, &budget); input.put(if image { "image.svg" } else { "document.tex" }, source.as_bytes().to_vec()).map_err(|e| e.to_string())?;
        for (name, data) in assets { input.put(&name, data).map_err(|e| e.to_string())?; }
        let output = Directory::new(true, &budget);
        let bundle = Directory::bundle(self.bundle.clone(), false, &budget);
        if !format && !image { bundle.put("latex.fmt", self.format.clone()).map_err(|e| e.to_string())?; }
        let fonts = Directory::bundle(self.bundle.clone(), true, &budget);
        fonts.put("notebook-fonts.tsv", self.fonts.clone()).map_err(|e| e.to_string())?;
        let log = Log::default();
        let mut builder = WasiCtxBuilder::new();
        builder.env("TECTONIC_CACHE_DIR", "/output").map_err(|e| e.to_string())?
            .env("TECTONIC_FONT_DIR", "/fonts").map_err(|e| e.to_string())?
            .env("SOURCE_DATE_EPOCH", &date.to_string()).map_err(|e| e.to_string())?;
        let wasi = builder.build();
        wasi.set_stdout(Box::new(WritePipe::new(log.clone()))); wasi.set_stderr(Box::new(WritePipe::new(log.clone())));
        for (name, dir) in [("/input", input), ("/output", output.clone()), ("/bundle", bundle), ("/fonts", fonts)] {
            wasi.push_preopened_dir(Box::new(dir), name).map_err(|e| e.to_string())?;
        }
        // AOT WebAssembly uses this one fixed mapping. Each guest load/store is
        // bounds checked; memory.grow changes its extent without reallocating.
        let mut arena = memmap2::MmapMut::map_anon(if format { 512*1024*1024 } else { LINEAR_BYTES }).map_err(|e| e.to_string())?;
        let mut native = NativeState { wasi, started, timeout: timeout.min(Duration::from_secs(30)), cancelled, failure: None };
        let mut memory_bytes = 0;
        let status = unsafe { nb_engine_run((&mut native as *mut NativeState).cast(), arena.as_mut_ptr(), arena.len(), &mut memory_bytes, operation) };
        drop(arena);
        if let Some(error) = native.failure { return Err(format!("{error}\n{}", String::from_utf8_lossy(&log.0.lock().unwrap()))); }
        drop(native.wasi);
        check()?;
        let log = String::from_utf8_lossy(&log.0.lock().unwrap()).into_owned();
        if status != 0 { return Err(format!("typesetter_error({status}): {log}")); }
        if format { return Ok(Output { pdf: output.take("latex.fmt").ok_or_else(|| format!("typesetter_no_format: {log}"))?, synctex: vec![], log, memory_bytes }); }
        let pdf = output.take(if image { "image.pdf" } else { "document.pdf" }).ok_or_else(|| format!("typesetter_no_pdf: {log}"))?;
        let synctex = output.take("document.synctex.gz").unwrap_or_default();
        if !pdf.starts_with(b"%PDF-") || pdf.len() > 16*1024*1024 || synctex.len() > 4*1024*1024 { return Err("typesetter_output_limit".into()); }
        Ok(Output { pdf, synctex, log, memory_bytes })
    }
}
